framework:
    messenger:
        failure_transport: failed

        transports:
            account:
                dsn: '%env(AMPQ_URL)%'
                options:
                    exchange:
                        name: '%env(ACCOUNT_QUEUE)%'
                    queues:
                        '%env(ACCOUNT_QUEUE)%': ~

        routing:
            App\Command\Account\AccountCommand: account

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
